server:
  port: 8080

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

cloud:
  gateway:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

    # Optional: Route manually if needed
    # routes:
    #   - id: auth-service
    #     uri: lb://auth-service
    #     predicates:
    #       - Path=/auth/**
    #   - id: task-service
    #     uri: lb://task-service
    #     predicates:
    #       - Path=/task/**

