server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: root
    password: Sonu123@

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
