server:
  port: 8082

spring:
  application:
    name: task-service
  datasource:
    url: jdbc:mysql://localhost:3306/taskdb
    username: root
    password: password

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
